[project]
name = "demodatarepo"
version = "0.1.0"
description = "It's a data project demo for testing out the SchemaGuard."
readme = "README.md"
authors = [
    { name = "gazi04", email = "gazmendhalili2016@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.12.5",
    "dbt-postgres>=1.11.0",
]
